### PR TITLE
Editor fix

### LINKED ISSUE #121: Parent editors aren't printing
Not sure why yet.

Probably need to check, and add a test for, the `suppress` method (related to substitution).

### PR DESCRIPTION
**Pull request by bdarcus**
#121 is driving me crazy, but I've at least narrowed the problem to the `suppress_component` method, and specifically to the logic for editors.

-----------------------

I think fixing this may require reverting an earlier refactor.

The `reference.author()` method should only return an author, and the substitution should happen somewhere else, and explicitly.

It could be I move `get_author_substitute` to `InputReference`, which seems the natural place to put it. But that likely means it would be hard-coded?

Or maybe not; could return a hash table of the substitution options, and let the processor select the correct one based on the style config?

### CODE REVIEW

File: processor/src/lib.rs [hunk 1]
```diff
@@ -576,21 +577,15 @@ impl Processor {
...
-            }
-            TemplateComponent::Title(title) => {
-                let title_type = title.title.clone();
-                // TODO need more logic here
-                (title_type == Titles::Primary && author_substitute.is_some())
-                    && (author_substitute.unwrap().1 == SubstituteKey::Title)
+                // FIXME this incorrectly suppresses the editor role
+                author_substitute.is_some()
+                    && author_substitute.unwrap().1 == SubstituteKey::Editor
+                    && role == ContributorRole::Editor
```
Comment (bdarcus) [inline processor/src/lib.rs:588]: This change makes it a little more elegant, but it's still wrong!
